name: PR - Basic Build & Test

on:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup NuGet sources
        uses: SkylineCommunications/_ReusableWorkflows/.github/actions/setup-nuget-sources@main
        with:
          repository-owner: ${{ github.repository_owner }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-skyline: 'false'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Unit tests
        shell: bash
        run: dotnet test --no-build --filter "TestCategory!=IntegrationTest&TestCategory!=IntegrationTests"
